from django.shortcuts import render
import random

# Create your views here.

ROASTS = [
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "If I had a dollar for every time you said something smart, I’d be broke.",
    "I’d agree with you but then we’d both be wrong.",
    "You're proof that even evolution can take a wrong turn.",
    "You're like a software update. Whenever I see you, I think, 'Not now.'",
    "You bring everyone so much joy when you leave the room.",
    "I’ve seen salads dressed better than you.",
    "You're not stupid; you just have bad luck thinking.",
    "Your secrets are always safe with me. I never even listen when you tell me them.",
    "You have the perfect face for radio.",
    "I would agree with you, but then we’d both be wrong.",
    "Your only chance of getting laid is to crawl up a chicken's butt and wait.",
    "You’re like a phone with no signal—useless.",
    "I would explain it to you, but I left my English-to-Dingbat dictionary at home.",
    "You're the human equivalent of a participation trophy.",
    "If I wanted to hear from an idiot, I’d just look in the mirror.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "You have the perfect face for radio.",
    "You couldn't pour water out of a boot if the instructions were on the heel.",
    "You're the reason people are afraid to use the internet.",
    "If I had a dollar for every time you said something dumb, I’d be a billionaire.",
    "You bring everyone so much joy when you leave the room.",
    "You’re like a cloud. When you disappear, it’s a beautiful day.",
    "You’re proof that even evolution can take a wrong turn.",
    "I’ve seen better combinations at a burger joint.",
    "You have the IQ of a rock, and the personality to match.",
    "Your brain is like a web browser – multiple tabs open but no idea where the music is coming from.",
    "You're like a software update: you appear out of nowhere, take forever to install, and then break everything.",
    "You're like a participation trophy—everyone has one but no one knows why.",
    "It’s not that you’re ugly. You’re just... your face doesn’t inspire anything good.",
    "You are like a cloud in a storm—always hanging around but never helpful.",
    "If I had a nickel for every time you said something dumb, I could afford a rocket ship to get away from you.",
    "You're a few sandwiches short of a picnic.",
    "You’re the human equivalent of a typo.",
    "You have the personality of a dial-up internet connection.",
    "You're proof that the brain isn’t the most important organ.",
    "You're the reason the gene pool needs a lifeguard.",
    "You're not stupid; you just have a lot of bad luck thinking.",
    "If you were any more dense, we could turn you into a black hole.",
    "You're like a Wi-Fi signal—strong at first, but then just disappears.",
    "You’re not the sharpest tool in the shed, but you’re definitely the one with the most rust.",
    "You bring nothing to the table, except the table.",
    "Your existence is like an unwanted pop-up ad.",
    "You're the human equivalent of a broken pencil—pointless.",
    "You must be the square root of negative one—because you can't be real.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "Your brain is like a website with a 404 error.",
    "Your parents must have been astronauts because you're spaced out.",
    "I would agree with you, but then we’d both be wrong.",
    "Your face makes onions cry.",
    "You're like a cloud, but you don't bring rain—just confusion.",
    "You're so dense, light bends around you.",
    "You couldn’t organize a one-car parade.",
    "You're the human equivalent of a participation trophy.",
    "I’d agree with you, but then we’d both be wrong.",
    "Your charm is like an expired coupon—useless.",
    "If I had a brain, I’d be dangerous. But then again, you wouldn't have that problem.",
    "You have the perfect face for a disguise.",
    "You're like a broken pencil. Pointless.",
    "If laziness were an Olympic sport, you’d come in fourth so you wouldn’t have to walk up to the podium.",
    "You bring joy when you leave the room.",
    "I would agree with you, but then we'd both be wrong.",
    "You’re like a cloud. When you disappear, it’s a beautiful day.",
    "You're as useful as a screen door on a submarine.",
    "I don’t have the time or the crayons to explain this to you.",
    "You're the kind of person who would trip over a wireless connection.",
    "You must be the square root of -1 because you’re imaginary.",
    "You couldn’t pour water out of a boot if the instructions were on the heel.",
    "You’re the reason we have instructions on shampoo bottles.",
    "You're the type of person who’d look at a cup of coffee and wonder why it's so bitter.",
    "You're the human version of a typo.",
    "You have the mental agility of a rock.",
    "You're like a broken pencil—pointless.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "You remind me of a cloud. When you disappear, everything gets better.",
    "You're as useful as a screen door on a submarine.",
    "Your brain is like a web browser, with 50 tabs open and none of them working.",
    "You have the IQ of a rock and the personality of a brick wall.",
    "If I had a penny for every time you said something dumb, I’d be rich.",
    "You're the reason the gene pool needs a lifeguard.",
    "You couldn't pour water out of a boot if the instructions were on the heel.",
    "You have the charisma of a wet paper towel.",
    "You're like a cloud, but without the rain or the shade.",
    "Your best feature is the distance between us.",
    "You couldn’t organize a one-car parade.",
    "You must be a magician, because whenever I look at you, everyone else disappears. Then I realize it's because they couldn’t bear to watch.",
    "You have the personality of a dial-up internet connection.",
    "You remind me of a phone with no signal—pointless.",
    "You're like a Wi-Fi signal that never connects.",
    "You have the humor of a brick wall.",
    "If I had a dollar for every time you said something dumb, I’d have enough to pay for your education.",
    "You're the reason people have trust issues.",
    "You're the human version of a forgotten password.",
    "You must be the reason for the shortage of brain cells.",
    "Your ideas are like the weather in a desert—nonexistent.",
    "You're the reason people fear looking in mirrors.",
    "If brains were taxed, you’d get a refund.",
    "You’re the human equivalent of a blank page—no substance.",
    "You should be a professional in procrastination. You’re great at it.",
    "You're like a candle. When you burn out, no one cares.",
    "If I had a nickel for every time you said something intelligent, I’d still be broke.",
    "You’re like a sloth on a caffeine high.",
    "You’re the human version of a 404 error.",
    "You're like a snowstorm, always cold and never helpful.",
    "If you were any dumber, I'd have to water you.",
    "You must be the reason for the brain drain.",
    "You're like a Wi-Fi router—people just want to disconnect from you.",
    "You're proof that even a broken clock is right twice a day.",
    "You must have a PhD in idiocy.",
    "If I could rearrange the alphabet, I’d put U and I together—but I don’t want to ruin it.",
    "You’re the kind of person who'd trip over a wireless connection.",
    "Your brain is like a cup of coffee: strong, but gets cold fast.",
    "If your IQ was any lower, we’d be in negative numbers.",
    "You’re the human version of a participation award.",
    "You're not stupid, you just have bad luck thinking.",
    "You have the social skills of a door handle.",
    "You couldn’t pour water out of a boot if the instructions were on the heel.",
    "If I had a brain, I’d be dangerous. But then again, you wouldn’t have that problem.",
    "You're like a broken pencil: pointless.",
    "You're the reason they put instructions on shampoo bottles.",
    "I’d explain it to you, but I left my English-to-Dingbat dictionary at home.",
    "You're like a GPS that gives wrong directions.",
    "If you were any more clueless, you’d be a blank page.",
    "You're the human version of a bad Wi-Fi connection.",
    "You’re like a shadow—always there but never helpful.",
    "If brains were taxed, you’d get a refund.",
    "You're proof that even evolution can take a wrong turn.",
    "You’re the human equivalent of a broken pencil—pointless.",
    "Your brain is like a website with too many tabs open.",
    "You're like a cloud: when you disappear, it’s a good day.",
    "If your brain was dynamite, there wouldn’t be enough to blow your hat off.",
    "You remind me of a cloud. When you disappear, it’s a beautiful day.",
    "You're the reason the gene pool needs a lifeguard.",
    "You're like a phone with no signal—useless.",
    "I don’t know if I should call you an idiot or a genius, because both make me laugh.",
    "If your IQ was any lower, you’d have to sit on the ground to pick up your thoughts.",
    "You're the human version of a typo.",
    "You have the charisma of a potato.",
    "You're like a cloud, but without the rain.",
    "If I could give you a medal for being the dumbest person alive, I would, but you’d probably lose it.",
    "You must be the reason people fear looking in mirrors.",
    "You’re proof that even a broken clock is right twice a day.",
    "You're like a software update: always unexpected and inconvenient.",
    "You're like a snowstorm: cold and useless.",
    "You have the personality of a wet sponge.",
    "You couldn’t pour water out of a boot if the instructions were on the heel.",
    "You're the kind of person who would trip over a wireless connection.",
    "You’re like a lightbulb in a dark room—there’s just no reason for you to be here.",
    "You're like a puzzle with half the pieces missing.",
    "You're the reason we need a warning label for stupidity.",
    "You're like a forgotten password—pointless.",
    "You have the ability to turn any situation into an awkward one.",
    "If you were any more clueless, you'd be a GPS with no signal.",
    "Your brain is on standby mode all the time.",
    "If your brain was made of helium, it wouldn’t even float.",
    "You must be the reason we have a 'no returns' policy.",
    "You're like a software update: nobody asked for you.",
    "You have the charisma of a damp rag.",
    "You could be the human equivalent of a backup hard drive: full of data but none of it makes sense.",
    "You’re the human version of a malfunctioning vending machine.",
    "You're like a Wi-Fi connection with no password—open to everyone but no one wants to use you.",
    "If I had a dollar for every time you said something brilliant, I'd still be poor.",
    "You're the kind of person who needs a map to find their way out of a paper bag.",
    "You must be a magician, because whenever I look at you, everyone else disappears. Then I realize it's because they couldn’t bear to watch.",
    "You have the personality of a cardboard box.",
    "If brains were dynamite, you wouldn’t have enough to blow your nose.",
    "You're as useful as a screen door on a submarine.",
    "If I could rearrange the alphabet, I'd put U and I together, but I don't want to ruin it.",
    "You’re like a forgotten password—completely useless.",
    "You have the charm of a wet towel.",
    "You're like a snowstorm—everyone’s excited at first, then they realize you’re just cold and inconvenient.",
    "You couldn't pour water out of a boot if the instructions were on the heel.",
    "You’re the kind of person who'd trip over a wireless connection.",
    "You have the creativity of a paperclip.",
    "You're like a broken pencil—pointless.",
    "You must be a magician, because whenever I look at you, everyone else disappears.",
    "You have the wit of a potato.",
    "If I had a penny for every time you said something funny, I’d be in debt.",
    "You bring nothing to the table except confusion and bad jokes.",
    "You're the reason people check their phones in the middle of conversations.",
    "You have the emotional range of a teaspoon.",
    "You couldn't organize a one-car parade.",
    "You’re like a cloud, but without the rain or the shade.",
    "You're like a GPS that always takes you the wrong way.",
    "You remind me of a broken pencil—pointless.",
    "You're like a storm—when you show up, everything gets messy.",
    "If you were any dumber, I’d have to water you.",
    "You remind me of a cat—cute at first, but then you scratch me.",
    "You’re like a bad Wi-Fi connection—everyone's trying to disconnect.",
    "You have the depth of a puddle.",
    "You couldn’t win a race with a rock.",
    "You’re the reason the gene pool needs a lifeguard.",
]

TOASTS = [
    "You have a smile that could outshine a thousand suns!",
    "If kindness were a superpower, you'd be in the Avengers!",
    "You make the world a better place just by being in it!",
    "Your positivity is like a magnet that draws people in!",
    "You’re like a sunrise, always bringing warmth and light into my day.",
    "Your kindness is a rare gem, and I’m lucky to have found it.",
    "If I had a flower for every time you made me smile, I’d be walking through a garden.",
    "You have the ability to brighten any room just by walking into it.",
    "You’re like a warm cup of tea on a cold day—comforting and perfect.",
    "Your presence is like a hug for the soul.",
    "If happiness had a face, it would look like yours.",
    "You’re the kind of person who makes everyone feel special.",
    "Your heart is as big as your smile, and both are contagious.",
    "You bring out the best in everyone around you.",
    "You’re the sparkle in a world that sometimes feels too dull.",
    "Your positivity is a breath of fresh air in a sometimes heavy world.",
    "You’re like a rainbow after a storm—bringing color and joy.",
    "Every time I’m with you, I feel like the luckiest person alive.",
    "You make the world a better place just by being you.",
    "You have a way of making even the ordinary extraordinary.",
    "When you laugh, the whole world laughs with you.",
    "Your energy is so infectious; you make life feel like a celebration.",
    "You make people feel heard, seen, and valued.",
    "Your kindness can turn any bad day into a good one.",
    "You’re a diamond in a world full of stones.",
    "Your sense of humor lights up even the darkest moments.",
    "You have a heart of gold and a spirit that shines.",
    "You make life feel like it’s full of possibilities.",
    "You have the rare ability to make everyone around you feel better about themselves.",
    "You’re the kind of person who turns ordinary moments into special ones.",
    "Your kindness has a ripple effect, spreading joy everywhere you go.",
    "Your smile can light up even the darkest days.",
    "You're the kind of person who makes the world a little brighter with every step you take.",
    "You make everything you touch better with your positive energy.",
    "You're the type of person people feel lucky to know.",
    "You have a heart that never stops giving.",
    "You are the kind of person who makes people believe in the good in the world.",
    "You are a walking, talking ray of sunshine.",
    "You inspire people to be better just by being yourself.",
    "Your joy is contagious, and it makes everyone around you feel happier.",
    "You're the reason people believe in the goodness of humanity.",
    "You’re the type of person who can lift anyone’s spirits in an instant.",
    "Your sense of humor is a gift to everyone who hears it.",
    "You have a way of making even the hardest days feel a little easier.",
    "You’re the person everyone goes to for support because they know you’ll always be there.",
    "You make the world feel like a brighter, better place.",
    "You have a smile that could light up the darkest night.",
    "You make every day feel like it’s worth celebrating.",
    "Your heart is as big as your smile, and both make the world a better place.",
    "You're the kind of person who turns an ordinary day into a happy one.",
    "You spread joy wherever you go, and it's a gift to everyone around you.",
    "You are a shining example of how kindness can change the world.",
    "You have the ability to make people feel good about themselves without even trying.",
    "Your positive energy makes everything better.",
    "You are like a breath of fresh air, always making everything better.",
    "Your laughter is the best music, and everyone loves to hear it.",
    "You make every moment special just by being yourself.",
    "Your kindness is a light in a sometimes dim world.",
    "You have a soul that makes people want to be better.",
    "You brighten up even the cloudiest days with your smile.",
    "You turn every challenge into an opportunity to shine.",
    "Your presence is like a warm hug that everyone appreciates.",
    "You’re the type of person who makes everyone feel like they matter.",
    "Your positive attitude makes even the hardest days easier.",
    "You bring so much joy into the world, one smile at a time.",
    "Your heart is as beautiful as your spirit.",
    "You are the kind of person who makes everyone else feel loved and appreciated.",
    "You have the ability to make people laugh when they need it the most.",
    "You make life feel like a big, beautiful adventure.",
    "You have a way of making everything around you brighter.",
    "Your energy is like a magnet—people can’t help but be drawn to you.",
    "You are a true inspiration, reminding everyone to be kind and caring.",
    "Your wisdom and warmth make you someone everyone looks up to.",
    "You bring a sense of calm to every storm.",
    "You have the unique ability to make anyone feel like a million bucks.",
    "You light up the world simply by being in it.",
    "Your smile is the best accessory you could ever wear.",
    "Your spirit makes everything around you better.",
    "You always know how to lift people’s spirits with just a word or a smile.",
    "You are the reason people believe that good things still happen.",
    "You make the world a better place simply by being in it.",
    "You have the power to make people feel seen and understood.",
    "You make every day brighter, just by being you.",
    "Your laughter is the best remedy for any bad day.",
    "You have the heart of a champion and the soul of a poet.",
    "Your kindness leaves a lasting impact on everyone you meet.",
    "You’re a ray of sunshine in a world that needs more of it.",
    "You make everything feel possible with your optimism and belief.",
    "You make people feel like they are enough, just as they are.",
    "You turn ordinary moments into extraordinary memories.",
    "Your positivity is a gift to everyone who knows you.",
    "You’re like a cup of coffee—energizing and warming the soul.",
    "You are the reason people keep smiling through tough times.",
    "Your presence is a reminder that there’s always something to be grateful for.",
    "You have a heart that’s full of love, and it shows in everything you do.",
    "You brighten the lives of everyone you meet.",
    "You spread happiness everywhere you go, and it’s a beautiful thing.",
    "You’re the kind of person who makes life feel like a celebration.",
    "You have the kind of soul that makes the world better just by existing.",
    "You make everyone around you feel special and important.",
    "Your kindness and warmth are what make you stand out in the best way.",
    "Your smile is like sunshine—it can light up even the darkest days.",
    "You have a way of making everyone feel at ease and comfortable.",
    "You are a reminder that goodness and kindness still exist in the world.",
    "Your presence makes every place feel warmer and more welcoming.",
    "You bring joy and positivity wherever you go.",
    "Your kindness is like a beacon that shines brightly for all to see.",
    "You have a heart full of love and a soul that radiates warmth.",
    "Your energy lights up the room in a way that nothing else can.",
    "You’re a rare gem, and the world is lucky to have you in it.",
    "Your kindness is a reminder that small acts of love can change the world.",
    "You make people feel seen, heard, and valued in ways they can’t forget.",
    "You make everyone around you feel like they are the most important person in the room.",
    "Your kindness is so genuine, it touches everyone you meet.",
    "You have the unique ability to make others feel better just by being in their presence.",
    "Your positivity is contagious, and it lifts up everyone around you.",
    "You have a heart that is pure, and it shows in everything you do.",
    "You have the power to turn someone's bad day into a good one, simply by being yourself.",
    "Your energy is the kind that makes people want to do better and be better.",
    "You are the person everyone turns to for support, comfort, and wisdom.",
    "You have a way of making the world seem just a little bit better.",
    "Your sense of humor is one of your most special qualities.",
    "You light up every conversation with your positivity and warmth.",
    "You have a heart full of generosity that makes everyone feel loved.",
    "You have the remarkable ability to make everyone feel at home.",
    "You’re a bright light in a world that sometimes feels too dim.",
    "You inspire others to be kind, loving, and patient.",
    "You have the kind of spirit that makes people feel like they can conquer anything.",
    "Your wisdom and kindness make you a true treasure.",
    "You are the type of person who makes the world a better place simply by being in it.",
    "You bring so much joy into the lives of everyone you meet.",
    "You are the reason so many people smile every day.",
    "Your presence makes everything feel a little brighter and a little warmer.",
    "You have the gift of making people feel important and valued.",
    "You are a source of constant inspiration to everyone who knows you.",
    "You make the world a better place, just by being your kind and loving self.",
    "Your love for others is so evident, and it touches everyone around you.",
    "You have a gift for making people feel like they are the best version of themselves.",
    "Your presence is like a warm blanket on a cold day.",
    "You have a smile that can instantly lift someone's mood.",
    "You radiate warmth and positivity wherever you go.",
    "Your laugh is one of the best sounds in the world.",
    "You are a natural born leader who makes the world a better place.",
    "You make the people around you feel like they are worth more than gold.",
    "You have a way of making everyone feel included and appreciated.",
    "Your joy is a reminder that life is beautiful, no matter what.",
]

def home(request):
    #return render(request, 'home.html')
    response_type = random.choice(['roast','toast'])
    if response_type == 'roast':
        message = random.choice(ROASTS)
    else:
        message = random.choice(TOASTS)
    
    return render(request, 'home.html', {'message': message, 'response_type': response_type})
